<?php
/**
 * @file
 * Responsive panels layouts for Panopoly.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function webflow_layouts_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_ctools_plugin_post_alter().
 *
 * @param $plugin
 * @param $info
 */
function webflow_layouts_ctools_plugin_post_alter(&$plugin, &$info) {
  // Switch Panopoly Layouts to webflow Layouts.
  if ($info['type'] == 'layouts') {
    if (strpos($plugin['theme'], 'webflow_') === FALSE) {
      $new_name = 'webflow_' . $plugin['theme'];
      $path = drupal_get_path('module', 'webflow_layouts') . '/plugins/layouts/' . $new_name;
      if (file_exists($path)) {
        $plugin['theme'] = $new_name;
        $plugin['file'] = 'webflow_' . $plugin['file'];
        $plugin['path'] = $path;
        $plugin['icon'] = 'webflow-' . $plugin['icon'];
        unset($plugin['css']);
      }
    }
  }
}